import 'dart:io';
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:image_picker/image_picker.dart';
import 'package:kanante_app/models/comment_model.dart';
import 'package:kanante_app/models/publication_model.dart';
import 'package:kanante_app/models/user_model.dart';
import 'package:kanante_app/services/firebase_service.dart';
import 'package:intl/intl.dart';

class CommentsScreen extends StatefulWidget {
  final Publication publication;
  const CommentsScreen({super.key, required this.publication});

  @override
  State<CommentsScreen> createState() => _CommentsScreenState();
}

class _CommentsScreenState extends State<CommentsScreen> {
  final FirebaseService _firebaseService = FirebaseService();
  final _commentController = TextEditingController();
  final ImagePicker _picker = ImagePicker();
  XFile? _pickedImage;
  bool _isUploading = false;
  UserModel? _currentUser;

  @override
  void initState() {
    super.initState();
    _loadCurrentUser();
  }

  Future<void> _loadCurrentUser() async {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      final userModel = await _firebaseService.getUserProfile(user.uid);
      if (mounted) {
        setState(() {
          _currentUser = userModel;
        });
      }
    }
  }

  Future<void> _pickImage() async {
    final pickedFile = await _picker.pickImage(source: ImageSource.gallery);
    if (pickedFile != null) {
      setState(() {
        _pickedImage = pickedFile;
      });
    }
  }

  Future<void> _postComment() async {
    if (_commentController.text.trim().isEmpty && _pickedImage == null) {
      return; // Do nothing if there's no content
    }
    if (_currentUser == null) return; // Cannot post without user info

    setState(() => _isUploading = true);

    try {
      String? imageUrl;
      if (_pickedImage != null) {
        // In a real app, the path should be more unique.
        final ref = _firebaseService.storage.ref().child('comment_images/${DateTime.now().millisecondsSinceEpoch}');
        final uploadTask = await ref.putFile(File(_pickedImage!.path));
        imageUrl = await uploadTask.ref.getDownloadURL();
      }

      final newComment = CommentModel(
        id: '', // Will be generated by push()
        userId: _currentUser!.id,
        userName: _currentUser!.name,
        userImageUrl: _currentUser!.profileImageUrl,
        text: _commentController.text.trim(),
        imageUrl: imageUrl,
        timestamp: DateTime.now(),
      );

      await _firebaseService.addCommentToPublication(widget.publication.id, newComment);
      
      _commentController.clear();
      setState(() {
        _pickedImage = null;
        // Ideally, we should get the updated publication from the stream
        // For now, we manually add the comment to the local list for immediate UI update
        widget.publication.comments.add(newComment);
      });

    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error al publicar comentario: $e')),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isUploading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Comentarios (${widget.publication.comments.length})'),
      ),
      body: Column(
        children: [
          Expanded(
            child: widget.publication.comments.isEmpty
                ? const Center(child: Text('No hay comentarios. ¡Sé el primero!'))
                : ListView.builder(
                    padding: const EdgeInsets.all(8),
                    itemCount: widget.publication.comments.length,
                    itemBuilder: (context, index) {
                      final comment = widget.publication.comments[index];
                      return _buildCommentTile(comment);
                    },
                  ),
          ),
          const Divider(height: 1),
          _buildCommentInput(),
        ],
      ),
    );
  }

  Widget _buildCommentTile(CommentModel comment) {
    return ListTile(
      leading: CircleAvatar(
        backgroundImage: comment.userImageUrl != null ? NetworkImage(comment.userImageUrl!) : null,
        child: comment.userImageUrl == null ? const Icon(Icons.person) : null,
      ),
      title: Text(comment.userName, style: const TextStyle(fontWeight: FontWeight.bold)),
      subtitle: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(comment.text),
          if (comment.imageUrl != null)
            Padding(
              padding: const EdgeInsets.only(top: 8.0),
              child: Image.network(comment.imageUrl!),
            ),
        ],
      ),
      trailing: Text(DateFormat('dd/MM').format(comment.timestamp), style: Theme.of(context).textTheme.bodySmall),
    );
  }

  Widget _buildCommentInput() {
    if (_currentUser == null) {
      return const SizedBox.shrink(); // Don't show input if user is not loaded
    }
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Column(
        children: [
           if (_pickedImage != null)
            Stack(
              children: [
                Image.file(File(_pickedImage!.path), height: 100),
                Positioned(
                  top: 0,
                  right: 0,
                  child: IconButton(
                    icon: const Icon(Icons.remove_circle, color: Colors.red),
                    onPressed: () => setState(() => _pickedImage = null),
                  ),
                ),
              ],
            ),
          Row(
            children: [
              IconButton(
                icon: const Icon(Icons.photo_camera),
                onPressed: _isUploading ? null : _pickImage,
              ),
              Expanded(
                child: TextField(
                  controller: _commentController,
                  decoration: const InputDecoration(
                    hintText: 'Añadir un comentario...',
                    border: InputBorder.none,
                  ),
                  onSubmitted: (_) => _postComment(),
                ),
              ),
              _isUploading
                  ? const CircularProgressIndicator()
                  : IconButton(
                      icon: const Icon(Icons.send),
                      onPressed: _postComment,
                    ),
            ],
          ),
        ],
      ),
    );
  }
}
