import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:kanante_app/models/support_ticket_model.dart';
import 'package:kanante_app/services/firebase_service.dart';
import 'package:kanante_app/models/user_model.dart';
import 'package:kanante_app/widgets/auth/primary_auth_button.dart';

class FeedbackFormScreen extends StatefulWidget {
  const FeedbackFormScreen({super.key});

  @override
  State<FeedbackFormScreen> createState() => _FeedbackFormScreenState();
}

class _FeedbackFormScreenState extends State<FeedbackFormScreen> {
  final _formKey = GlobalKey<FormState>();
  final _firebaseService = FirebaseService();
  final _subjectController = TextEditingController();
  final _messageController = TextEditingController();

  bool _isAnonymous = false;
  bool _isLoading = false;

  @override
  void dispose() {
    _subjectController.dispose();
    _messageController.dispose();
    super.dispose();
  }

  Future<void> _submitFeedback() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    setState(() => _isLoading = true);

    try {
      final user = FirebaseAuth.instance.currentUser;
      UserModel? userProfile;

      if (user != null && !_isAnonymous) {
        userProfile = await _firebaseService.getUserProfile(user.uid);
      }

      final ticket = SupportTicket(
        ticketId: '', // Will be generated by Firebase push
        userId: _isAnonymous ? null : user?.uid,
        userName: _isAnonymous ? null : userProfile?.name,
        userRole: _isAnonymous ? null : userProfile?.accountType,
        subject: _subjectController.text.trim(),
        message: _messageController.text.trim(),
        createdAt: DateTime.now(),
      );

      await _firebaseService.createSupportTicket(ticket);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('¡Gracias! Hemos recibido tus comentarios.'),
            backgroundColor: Colors.green,
          ),
        );
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error al enviar el formulario: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Quejas y Sugerencias'),
        backgroundColor: Colors.teal,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              TextFormField(
                controller: _subjectController,
                decoration: const InputDecoration(
                  labelText: 'Asunto',
                  hintText: 'Ej: Sugerencia para la sección de perfil',
                  border: OutlineInputBorder(),
                ),
                validator: (value) =>
                    value == null || value.isEmpty ? 'El asunto es requerido.' : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _messageController,
                decoration: const InputDecoration(
                  labelText: 'Mensaje',
                  hintText: 'Describe tu queja o sugerencia detalladamente...',
                  border: OutlineInputBorder(),
                ),
                maxLines: 8,
                validator: (value) =>
                    value == null || value.isEmpty ? 'El mensaje es requerido.' : null,
              ),
              const SizedBox(height: 16),
              SwitchListTile(
                title: const Text('Enviar de forma anónima'),
                subtitle: const Text('Si no marcas esta opción, podremos responderte.'),
                value: _isAnonymous,
                onChanged: (value) {
                  setState(() {
                    _isAnonymous = value;
                  });
                },
                activeTrackColor: Colors.teal,
              ),
              const SizedBox(height: 24),
              PrimaryAuthButton(
                text: 'Enviar Comentarios',
                isLoading: _isLoading,
                onPressed: _submitFeedback,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
