// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI2hwfvp2HtMihwcKwwQ3qwrNTcE3x7vo',
    appId: '1:789041151727:web:3987138710f6d62ecea51a',
    messagingSenderId: '789041151727',
    projectId: 'kanante-app',
    authDomain: 'kanante-app.firebaseapp.com',
    databaseURL: 'https://kanante-app-default-rtdb.firebaseio.com',
    storageBucket: 'kanante-app.firebasestorage.app',
    measurementId: 'G-Q109ZK6ETR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv2e7KX-LGIQR0y4uDDzC_U7XdoBnol5I',
    appId: '1:789041151727:android:154509429f122c89cea51a',
    messagingSenderId: '789041151727',
    projectId: 'kanante-app',
    databaseURL: 'https://kanante-app-default-rtdb.firebaseio.com',
    storageBucket: 'kanante-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjCnAJqK7AE88za5XN7p9mPSlhrRq0I2c',
    appId: '1:789041151727:ios:8385262e31862b10cea51a',
    messagingSenderId: '789041151727',
    projectId: 'kanante-app',
    databaseURL: 'https://kanante-app-default-rtdb.firebaseio.com',
    storageBucket: 'kanante-app.firebasestorage.app',
    iosBundleId: 'com.example.kananteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjCnAJqK7AE88za5XN7p9mPSlhrRq0I2c',
    appId: '1:789041151727:ios:8385262e31862b10cea51a',
    messagingSenderId: '789041151727',
    projectId: 'kanante-app',
    databaseURL: 'https://kanante-app-default-rtdb.firebaseio.com',
    storageBucket: 'kanante-app.firebasestorage.app',
    iosBundleId: 'com.example.kananteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI2hwfvp2HtMihwcKwwQ3qwrNTcE3x7vo',
    appId: '1:789041151727:web:83bdc860a323806acea51a',
    messagingSenderId: '789041151727',
    projectId: 'kanante-app',
    authDomain: 'kanante-app.firebaseapp.com',
    databaseURL: 'https://kanante-app-default-rtdb.firebaseio.com',
    storageBucket: 'kanante-app.firebasestorage.app',
    measurementId: 'G-7CS4RX25SV',
  );

}